name: tutoring_app_flutter
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  validators: ^2.0.1
  shared_preferences: ^0.5.12+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/fonts/Nunito-Regular.ttf


