List<String> subjects = [
  "Math",
  "Science",
  "Geography",
  "History",
  "Social Science",
  "Algebra",
  "Calculus",
  "Trigonometry",
  "Physics",
  "Art",
  "Statistics",
  "Computer Science",
  "Computer Programming",
  "Biology",
  "Chemistry",
  "Engineering",
  "Accounting",
  "Business",
  "Law",
  "Kinesiology",
  "Medicine",
  "Animation",
  "3d Programming",
  "Early Childhood Education",
  "Psychology",
  "Psychiatry",
  "Electrical Engineering",
  "Marketing",
  "Human Resources",
  "Pharmacy",
  "Policing",
  "Project Management",
];
